### ISSUE TITLE
Windows 8 and SmartScreen

### ISSUE THREAD

**Issue by xannor** [zlepper/TechnicSolderHelper#23]
The default install will not fire up as normal on windows 8 unless you go to more info and select run anyway. This is not addressed on the post I found for your app on the technic pack forums. The only to solutions for this are to pre-publish sign the assembly with a supported CA signed cert, or to provide info about click more info and run anyway. The only problem with the second method is that this will have to be done any time the app updates. IF you do not have a CA backed signing cert then this would be your only approach. If you have a supported CA backed signing cert you can use the directions on the following post to setup a pre-publish assembly signing.

https://robindotnet.wordpress.com/2013/02/24/windows-8-and-clickonce-the-definitive-answer-2/

**Comment by zlepper** [comment]
I'm not making any money of this, and those certificates aren't free, so unless someone other than me are paying that is not happening.
Also there is a far easier way of signing the application since you can just have Visual Studio do it.
