### ISSUE TITLE
include lib files

### ISSUE THREAD

**Issue by zlepper** [zlepper/TechnicSolderHelper#31]
For really old instances of minecraft the lib files can't be found of forge's servers, so we have to include a zip file with them for the user. 
Should be part of the forge zip.

**Comment by TheDoctorsLife** [comment]
I would rather not have to download them unless I am making a pack. It might be better for them to be downloaded from your server upon creation of forge.zip

**Comment by zlepper** [comment]
Unlesz you are making a pack for 15.2 or before this shouldnt be a problem. And the files would be downloaded from my server without you even knowing and then included on the forge.zip.
Right now I assume this isn't even needed but I noticed that forge didn't have the files online anymore when someone tried to play big dig, and the files failed to download.

**Comment by TheDoctorsLife** [comment]
Sounds good.

**Comment by zlepper** [comment]
Seems the technic launcher just had issues with this for a moment. Everything seems to be working again.
