### ISSUE TITLE
Which version of Solder i have to use?

### ISSUE THREAD

**Issue by MineMalox** [zlepper/TechnicSolderHelper#47]
I would to use it with TechnicSolder but with version off it?

**Comment by zlepper** [comment]
0.7 or above. 
In generally you should always be using the latest version of TechnicSolder.

**Comment by MineMalox** [comment]
Yes but when i connect over MYSQL it says "Some tables appears to be missing in the database. Please reconstruct it and try again."

**Comment by TheDoctorsLife** [comment]
Then you are missing tables

**Comment by MineMalox** [comment]
But there all tables. The source says that the table clients arent there.
