### ISSUE TITLE
Unknown column 'min_java' in 'field list'.

### ISSUE THREAD

**Issue by Rhodizzle** [zlepper/TechnicSolderHelper#56]
Hey guys,

I'm attempting to use Modpack Helper to automat creation of a solder modpack. I have put in my mysql details and the test completes successfully, but once I click GO I get an unhandled exception that states 'Unknown column 'min_java' in 'field list'.

This happens whether I have a version selected in the Minimum Java Version field or not.

**Comment by zlepper** [comment]
What version of Solder do you have installed?

2015-06-25 5:32 GMT+02:00 Rhodizzle <notifications@github.com>:

**Comment by Rhodizzle** [comment]
0.7.1.1

**Comment by zlepper** [comment]
Update solder to 0.7.2.x

-----Original Message-----

**Comment by Rhodizzle** [comment]
That did it, thanks!
