### ISSUE TITLE
Lock up on packing

### ISSUE THREAD

**Issue by falconraptor** [zlepper/TechnicSolderHelper#57]
This program keeps locking up on waiting for the mods to finish packing after updating solder.

**Comment by zlepper** [comment]
Enable debug and try again. There should then be a log file on your desktop, send me that.

**Comment by falconraptor** [comment]
https://gist.github.com/falconraptor/c197df40ef74817561b0

**Comment by falconraptor** [comment]
it only locks up when i check use solder installation
here is another log if you want it: https://gist.github.com/falconraptor/6612d4d471f002970e16

**Comment by zlepper** [comment]
This should be fixed now acording to other people having the same issue.

**Comment by falconraptor** [comment]
I am having the same issue again: https://gist.github.com/falconraptor/2c4e68003e1d52177ffa
