### ISSUE TITLE
MD5s not correct

### ISSUE THREAD

**Issue by falconraptor** [zlepper/TechnicSolderHelper#59]
they are not correct when uploading to ftp and when not uploading to ftp

https://gist.github.com/falconraptor/3099f1e774d5f8aec62e
that is the debug log from technic solder and here is what the technic launcher is saying: 

[B#308] Starting download of http://repo.techraptor.us/mods/yalsm/yalsm-1.7.2-10.12.0.1024-2.1.3.zip, with 3 tries remaining
[B#308] Expected MD5: b002efae206626d50b11bfe78b74576a Calculated MD5: 1e3aeba4b04ec3f01d10f6e10769cd81
[B#308] Starting download of http://repo.techraptor.us/mods/yalsm/yalsm-1.7.2-10.12.0.1024-2.1.3.zip, with 2 tries remaining
[B#308] Expected MD5: b002efae206626d50b11bfe78b74576a Calculated MD5: 1e3aeba4b04ec3f01d10f6e10769cd81
[B#308] Starting download of http://repo.techraptor.us/mods/yalsm/yalsm-1.7.2-10.12.0.1024-2.1.3.zip, with 1 tries remaining
[B#308] Expected MD5: b002efae206626d50b11bfe78b74576a Calculated MD5: 1e3aeba4b04ec3f01d10f6e10769cd81

**Comment by zlepper** [comment]
Please try and download the file that's failing now and check the md5. I suspect this is caused by sine cached values by the technic platform.

**Comment by falconraptor** [comment]
if i readd the version of that mod to solder it fixes it until I update that mod again.

**Comment by zlepper** [comment]
Please check the md5 values, of the files. 
Currently I'm not clearing the cache, which results in things like these happening. 
Please download the file manually and check the md5 value of it. Then check what value is in your solder system. If these values are not the same, then please tell me their values, and send me the zip file that causes you issues.
