### ISSUE TITLE
Database is locked error

### ISSUE THREAD

**Issue by GeARCraft1** [zlepper/TechnicSolderHelper#62]
Hi! I'm using Windows and i'm recieving this error:
onsulte o final desta mensagem para obter detalhes sobre como chamar a 
depuração just-in-time (JIT) em vez desta caixa de diálogo.

************** Texto de Exceção **************
System.Data.SQLite.SQLiteException (0x80004005): database is locked
database is locked
   em System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   em System.Data.SQLite.SQLiteDataReader.NextResult()
   em System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   em System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   em System.Data.SQLite.SQLiteCommand.ExecuteReader()
   em System.Data.SQLite.SQLiteConnection.Schema_IndexColumns(String strCatalog, String strTable, String strIndex, String strColumn)
   em System.Data.SQLite.SQLiteConnection.GetSchema(String collectionName, String[] restrictionValues)
   em System.Data.SQLite.SQLiteDataReader.GetSchemaTable(Boolean wantUniqueInfo, Boolean wantDefaultValue)
   em System.Data.SQLite.SQLiteDataReader.GetSchemaTable()
   em System.Data.ProviderBase.SchemaMapping..ctor(DataAdapter adapter, DataSet dataset, DataTable datatable, DataReaderContainer dataReader, Boolean keyInfo, SchemaType schemaType, String sourceTableName, Boolean gettingData, DataColumn parentChapterColumn, Object parentChapterValue)
   em System.Data.Common.DataAdapter.FillMapping(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 schemaCount, DataColumn parentChapterColumn, Object parentChapterValue)
   em System.Data.Common.DataAdapter.FillFromReader(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 startRecord, Int32 maxRecords, DataColumn parentChapterColumn, Object parentChapterValue)
   em System.Data.Common.DataAdapter.Fill(DataTable[] dataTables, IDataReader dataReader, Int32 startRecord, Int32 maxRecords)
   em System.Data.Common.LoadAdapter.FillFromReader(DataTable[] dataTables, IDataReader dataReader, Int32 startRecord, Int32 maxRecords)
   em System.Data.DataTable.Load(IDataReader reader, LoadOption loadOption, FillErrorEventHandler errorHandler)
   em TechnicSolderHelper.SQL.ModListSqlHelper.GetTableInfoForEditing()
   em TechnicSolderHelper.SQL.DatabaseEditor..ctor()
   em TechnicSolderHelper.SolderHelper.button4_Click(Object sender, EventArgs e)
   em System.Windows.Forms.Control.OnClick(EventArgs e)
   em System.Windows.Forms.Button.OnClick(EventArgs e)
   em System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   em System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   em System.Windows.Forms.Control.WndProc(Message& m)
   em System.Windows.Forms.ButtonBase.WndProc(Message& m)
   em System.Windows.Forms.Button.WndProc(Message& m)
   em System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   em System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   em System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Sorry for my bad ortography (i need to do this fast)

**Comment by zlepper** [comment]
I need a bit more information:
What were you doing before the error appeared?
      Did you just finished packing the mods?
      Was this just after you opened the helper window?
Exactly what version of windows are you on?

**Comment by zlepper** [comment]
If you do not replay within 24 hours i will close the issue.

**Comment by GeARCraft1** [comment]
Ok. I just fixed it
