### ISSUE TITLE
Waiting for x mods to finish packing

### ISSUE THREAD

**Issue by Znubbis** [zlepper/TechnicSolderHelper#64]
Some useful information when it stops on "Waiting for x mods to finish packing" might be nice to have since it happens most time i try to run.

Also some last confirmation of what it will upload and to before it do update the database should be nice since for the moment none up my new releases gets past the last 4 mods.

**Comment by zlepper** [comment]
1) Unless it explicetly crashes, give it more time, and if that doesn't help, turn on debug mode, and send me the file it generates on your desktop. 
2) Can you zip me the mods you are trying to upload, and how you have configured solderhelper. 
3) Which mods are not updated to the database?

**Comment by Znubbis** [comment]
I finally figured it out the connection between the mods that fails.

They have : in the name of the mods in mcmod.info

On a side note, why don't authors that put tons of hours into a mod not take 5 min to add the correct info in their mcmod.info. During testing i got tired and added the info there myself to get rid of the dialogs (since it crashed it never saved it into the DB)

Kickass software btw, saves me tons of time when it works :+1:

**Comment by zlepper** [comment]
1) If something crashes i would love to have the crash report
2) Can you send me a mod with ":" in the name? My email is: hansen13579@gmai.com

**Comment by zlepper** [comment]
Also, use list mode to avoid a million dialogs

**Comment by zlepper** [comment]
I upload a version that should contain a fix for this. Please update and try again.

**Comment by Znubbis** [comment]
Works perfect, many thanks!
