### ISSUE TITLE
Unknown column 'minecraft_md5' in 'field list' when attempting to use remote MySQL db.

### ISSUE THREAD

**Issue by Routhinator** [zlepper/TechnicSolderHelper#67]
MySql.Data.MySqlClient.MySqlException: Unknown column 'minecraft_md5' in 'field list'
      at MySql.Data.MySqlClient.MySqlStream.ReadPacket () [0x00000] in <filename unknown>:0 
      at MySql.Data.MySqlClient.NativeDriver.GetResult (System.Int32& affectedRow, System.Int64& insertedId) [0x00000] in <filename unknown>:0 

This error occurs when attempting to use this tool with the latest version of Solder

**Comment by Routhinator** [comment]
It seems there is no minecraft_md5 table. It's called 'md5':

    MariaDB [solder]> show tables;
    +------------------+
    | Tables_in_solder |
    +------------------+
    | build_modversion |
    | builds           |
    | client_modpack   |
    | clients          |
    | keys             |
    | migrations       |
    | modpacks         |
    | mods             |
    | modversions      |
    | user_permissions |
    | users            |
    +------------------+
    11 rows in set (0.00 sec)

    MariaDB [solder]> SELECT * FROM mods;
    Empty set (0.01 sec)

    MariaDB [solder]> show columns from mods;
    +-------------+------------------+------+-----+---------------------+----------------+
    | Field       | Type             | Null | Key | Default             | Extra          |
    +-------------+------------------+------+-----+---------------------+----------------+
    | id          | int(10) unsigned | NO   | PRI | NULL                | auto_increment |
    | name        | varchar(255)     | NO   | UNI | NULL                |                |
    | description | text             | YES  |     | NULL                |                |
    | author      | varchar(255)     | YES  |     | NULL                |                |
    | link        | varchar(255)     | YES  |     | NULL                |                |
    | created_at  | timestamp        | NO   |     | 0000-00-00 00:00:00 |                |
    | updated_at  | timestamp        | NO   |     | 0000-00-00 00:00:00 |                |
    | pretty_name | varchar(255)     | NO   |     |                     |                |
    | donatelink  | varchar(255)     | YES  |     | NULL                |                |
    +-------------+------------------+------+-----+---------------------+----------------+
    9 rows in set (0.00 sec)
    
    MariaDB [solder]> show columns from modversions;
    +------------+------------------+------+-----+---------------------+----------------+
    | Field      | Type             | Null | Key | Default             | Extra          |
    +------------+------------------+------+-----+---------------------+----------------+
    | id         | int(10) unsigned | NO   | PRI | NULL                | auto_increment |
    | mod_id     | int(11)          | NO   |     | NULL                |                |
    | version    | varchar(255)     | NO   |     | NULL                |                |
    | md5        | varchar(255)     | NO   |     | NULL                |                |
    | created_at | timestamp        | NO   |     | 0000-00-00 00:00:00 |                |
    | updated_at | timestamp        | NO   |     | 0000-00-00 00:00:00 |                |
    +------------+------------------+------+-----+---------------------+----------------+
    6 rows in set (0.00 sec)

**Comment by zlepper** [comment]
Are you by chance on Linux or mac?

**Comment by Routhinator** [comment]
Linux - Debian Jessie 8

**Comment by zlepper** [comment]
Yeah, though so. It's because the linux version is not quite up to date. So you either have to recompile the program yourself, or wait for me to get home, which will be another 30 hours so i can access my linux install.

**Comment by Routhinator** [comment]
I can compile, anything special required to build this?

**Comment by zlepper** [comment]
Whatever mono requires. I usually uses monodevelop since it handles all the dependencies. I would also recommend updating to latest mono just to be safe.

**Comment by Routhinator** [comment]
Hmm, It's complaining about a missing icon when I attempt to build with monodevelop. Mono is one language I've never built. I will wait for your expertise to rebuild the binaries for Linux.

**Comment by zlepper** [comment]
I just uploaded the updated version. Try running the update script it and see if your issue is fixed.

**Comment by zlepper** [comment]
And progress on this?
