### ISSUE TITLE
Currently Doing: Waiting for <num> of mods to finish packing.

### ISSUE THREAD

**Issue by LyingCak3** [zlepper/TechnicSolderHelper#68]
Have been using your solder helper with great success but recently I was able to figure out the remote mysql upload and am having a weird issue with it.  When I first set up the upload I was using a user with ALL privileges for the DB but I decided to narrow down the scope of access and only gave it SELECT and INSERT for the tables needed in the db.  When I had it set to ALL the helper worked fine no issues, but now with the more restrictive access the helper still works, it still uploads everything and packs the mods for solder but then just hangs on 'Currently Doing: Waiting for <num> of mods to finish packing'.  

All the mods have been packed and the upload to the sql server finished.
![solder freeze](https://cloud.githubusercontent.com/assets/5199260/11480054/9af63d7e-9752-11e5-9ec0-4ab1d1e9ffc7.PNG)

Not a huge issue but I does require me to kill solder after a few minutes because I can't close it correctly.

**Comment by LyingCak3** [comment]
Forgot to mention that I am also skipping entering in a mod pack name and version.

**Comment by zlepper** [comment]
I assume you gave it access to UPDATE as part of insert too. 
Also I have no idea how it manages without working with a specific modpack, and it's not something i would recommend doing.

**Comment by LyingCak3** [comment]
I didn't give it update till after I made this post and it seems to be working fine now.  May want to post what permissions for mysql the user needs to work correctly, would help our some newer users.
