### ISSUE TITLE
Option to Lowercase All of the Mods

### ISSUE THREAD

**Issue by simdol** [zlepper/TechnicSolderHelper#70]
Hi,

Previously, I remember TechnicSolderHelper automatically renaming all of the mod's file name into the lowercase. However, at some point, the mod started to keep the uppercase for some of the mods, especially after having reset the database. (I infer this is due to mod author's fault as well for changing the .modinfo file.)

Could we please have the option to force lowercase for the all of the mods? It is very not convenient for me to manually put them into lowercase, edit the data, etc... as the data I have in the solder server differ from the data from the TechnicSolderHelper.

Thank you,

**Comment by zlepper** [comment]
It was forgotten in a refractor, and is actually a bug. 
Will fix now.

**Comment by zlepper** [comment]
And it should be fixed.
Please run the application and get the latest update and you should be good to go.

**Comment by simdol** [comment]
Thank you for the quick fix. I have applied the latest update and confirm that the latest build is functioning as it is intending to be.
