### ISSUE TITLE
Convert '_' Into '-"

### ISSUE THREAD

**Issue by simdol** [zlepper/TechnicSolderHelper#72]
During the solder mod categorization, I've encountered issue with 

> '_' 

character being invalid character on several mods. I suggest adding an option to convert 

> '_' 

into '-' or convert all of the '_' into '-' in default process without having to edit the local data.

Thank you.

EDIT: Apologies for line break. I had to do that due to markdown issue.

**Comment by simdol** [comment]
Hi,

Is there an update to this? This is a bug that I would like it to be addressed soon.

Thank you.

**Comment by GeARCraft1** [comment]
Sorry, I didn't understand your issue.

Thank you,
Gabriel

**Comment by TheDoctorsLife** [comment]
`_` are viewed as invailed by certain mods, he wants `_` to be auto converted to `-`

**Comment by simdol** [comment]
q

**Comment by zlepper** [comment]
Try updating and see if it fixed the issue.

**Comment by simdol** [comment]
@zlepper I am having issues with solder installation after upgrading the solder to the latest version. I am having Windows prompt that states, "Windows cannot access the specified device, path, or file. You may not have appropriate permissions to access the item." on the TechnicSolder.exe. I have attempted to reinstall them by removing AppData\Local\Apps\2.0\M7480R4C.JWC, and installing the solder again but no luck. I've attempted to run the program in administrator but the results are the same.

Could you please try the updated solder in Windows and see if the problem is reproduced on your end?

**Comment by zlepper** [comment]
It updated fine for me. 
What version of windows are you on?

**Comment by simdol** [comment]
@zlepper Windows 8.1 64bit. If you say so, it must be in my end. I will try to see what I could do to resolve this.

**Comment by simdol** [comment]
@zlepper I am sorry about this -- it looks like my HIPS denied your program due to invalid signature or according to their database. I will update this as soon as I resolve this problem in my end.

**Comment by simdol** [comment]
@zlepper  Negative, not fixed yet.

'1.7.10-1.7.10-0.2.0.34_beta'
'1.7.10-2.3.2_1.7.10'

**Comment by zlepper** [comment]
I'm not sure what you mean by the underscore character being invalid in some mods. From my perspective that seems to be a fully valid character. 
As far as the invalid characters go, i pretty much only remove characters that could somehow cause interference with downloading the zipped mod files, and the underscore is completely valid in that case. 
So i would really need a reason to go about stripping the underscore from the mod versions too.

**Comment by simdol** [comment]
@zlepper It is for the integrity of the version -- mod authors often change their scheme of the mod versioning (while they may keep the same scheme for filename / mod name or not), and end up having different mod version which sometimes in a large scale, makes keeping track of versions difficult.

Say mod author decided to release a version like, '1.7.10-1.0.2' and later decides to change it into '1.7.10_1.0.3' which seems fine in just one file / version, but it may become a problem when I want to specifically run a query in MySQL or in a program involving the version / mod name. The solder does not seem to interfere much with this apart from few versioning issues I see (confirmation required). Than in that case, I have to run multiple queries or have additional rule sets to avoid leaving out the half of it. Even there, what if the versioning involves '1.7.10_1.7.10-4.1_0.2'? It is simply just frustrating to be dealing with two different special characters.

This is just my perspective and I appreciate your perspective as underscore being valid character. If you do not see the need for such If that is the case, I can understand that.

**Comment by zlepper** [comment]
I agree that it's a problem that mod authors doesn't stay with one version scheme, which has also given me some headaches with another project i have been working on. 
So I just tried a small fix, since a proper fix would require changing 68 reference across the entire application. So please try updating and see if there is any improvement.

**Comment by simdol** [comment]
I confirm that the commit 812229e indeed does fix the issue. Thank you.
