### ISSUE TITLE
Origin Server Down

### ISSUE THREAD

**Issue by tenten8401** [zlepper/TechnicSolderHelper#74]
When packing the modpack, I'm recieving this error.
![Error](http://i.imgur.com/oJAZS58.png)

http://hastebin.com/yasedefisi.tex

Request: GET cloud.zlepper.dk/7za.exe HTTP/1.1

**Comment by zlepper** [comment]
Please try again now.

**Comment by tenten8401** [comment]
Oh, already downloaded 7za to appdata roaming whatever manually, but thanks for fixing it.
