### ISSUE TITLE
Designer not Working in VS2017

### ISSUE THREAD

**Issue by GabrielTK** [zlepper/TechnicSolderHelper#77]
Hey!
I've been trying to add GFS support to this project in a PR, but I can't even open a form in the designer.
Screenshot at [Imgur](https://i.imgur.com/Ng5J9za.png)
Sorry for being so brief 😄

**Comment by zlepper** [comment]
I just got it working in VS2017. Make sure you have the .Net Desktop Environment package installed for visual studio, that was all I needed to do:
![vs_installershell_2017-09-04_19-11-05](https://user-images.githubusercontent.com/1499810/30034909-d6437e3e-91a4-11e7-9eb1-451ce875f67f.png)

**Comment by GabrielTK** [comment]
![My current Install](https://i.imgur.com/QwlMelQg.png)

**Comment by zlepper** [comment]
Well, without the english errors i can't do anything given your original post :/

**Comment by GabrielTK** [comment]
While Openning:


> Esta versão do Visual Studio não pode abrir os projetos a seguir. Os tipos de projetos podem não estar instalados ou é possível que esta versão do Visual Studio não os aceite. 
> Para obter mais informações sobre como habilitar esses tipos de projetos ou migrar seus ativos de outra forma, consulte os detalhes do "Relatório de Migração" exibido depois de clicar em OK.
> 	 - Packages, "C:\Users\enric\Programacao\Projects\C#\TechnicSolderHelper\Packages.mdproj"
> 
> 
> Nenhuma alteração necessária
> Esses projetos podem ser abertos no Visual Studio 2015, Visual Studio 2013, Visual Studio 2012 e Visual Studio 2010 SP1 sem alterá-los.
> 	 - TechnicSolderHelper, "C:\Users\enric\Programacao\Projects\C#\TechnicSolderHelper\TechnicSolderHelper\TechnicSolderHelper.csproj"
> 	 - .nuget, ".nuget"
> 	 - TechnicSolderHelper, "C:\Users\enric\Programacao\Projects\C#\TechnicSolderHelper\TechnicSolderHelper.sln"
> 
> 

**(It actually worked today by miracle)**
